/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as HomeOfficeRouteImport } from './routes/home-office'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as StudioSlugRouteRouteImport } from './routes/$studioSlug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioSlugIndexRouteImport } from './routes/$studioSlug/index'
import { Route as StudioSlugKontaktRouteImport } from './routes/$studioSlug/kontakt'
import { Route as StudioSlugHomeOfficeRouteImport } from './routes/$studioSlug/home-office'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicWhatsappRouteImport } from './routes/api/public/whatsapp'
import { Route as ApiPublicPingRouteImport } from './routes/api/public/ping'
import { Route as AuthenticatedAdminStudiosRouteImport } from './routes/_authenticated/admin/studios'
import { Route as AuthenticatedAdminMarketingRouteImport } from './routes/_authenticated/admin/marketing'
import { Route as AuthenticatedAdminEinstellungenRouteImport } from './routes/_authenticated/admin/einstellungen'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin/clients'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin/calendar'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin/clients.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeOfficeRoute = HomeOfficeRouteImport.update({
  id: '/home-office',
  path: '/home-office',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSlugRouteRoute = StudioSlugRouteRouteImport.update({
  id: '/$studioSlug',
  path: '/$studioSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSlugIndexRoute = StudioSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioSlugRouteRoute,
} as any)
const StudioSlugKontaktRoute = StudioSlugKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => StudioSlugRouteRoute,
} as any)
const StudioSlugHomeOfficeRoute = StudioSlugHomeOfficeRouteImport.update({
  id: '/home-office',
  path: '/home-office',
  getParentRoute: () => StudioSlugRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicWhatsappRoute = ApiPublicWhatsappRouteImport.update({
  id: '/api/public/whatsapp',
  path: '/api/public/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPingRoute = ApiPublicPingRouteImport.update({
  id: '/api/public/ping',
  path: '/api/public/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminStudiosRoute =
  AuthenticatedAdminStudiosRouteImport.update({
    id: '/studios',
    path: '/studios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMarketingRoute =
  AuthenticatedAdminMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEinstellungenRoute =
  AuthenticatedAdminEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$studioSlug': typeof StudioSlugRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/home-office': typeof HomeOfficeRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/$studioSlug/home-office': typeof StudioSlugHomeOfficeRoute
  '/$studioSlug/kontakt': typeof StudioSlugKontaktRoute
  '/$studioSlug/': typeof StudioSlugIndexRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/einstellungen': typeof AuthenticatedAdminEinstellungenRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/studios': typeof AuthenticatedAdminStudiosRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/home-office': typeof HomeOfficeRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$studioSlug/home-office': typeof StudioSlugHomeOfficeRoute
  '/$studioSlug/kontakt': typeof StudioSlugKontaktRoute
  '/$studioSlug': typeof StudioSlugIndexRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/einstellungen': typeof AuthenticatedAdminEinstellungenRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/studios': typeof AuthenticatedAdminStudiosRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$studioSlug': typeof StudioSlugRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/home-office': typeof HomeOfficeRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/$studioSlug/home-office': typeof StudioSlugHomeOfficeRoute
  '/$studioSlug/kontakt': typeof StudioSlugKontaktRoute
  '/$studioSlug/': typeof StudioSlugIndexRoute
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/_authenticated/admin/einstellungen': typeof AuthenticatedAdminEinstellungenRoute
  '/_authenticated/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/_authenticated/admin/studios': typeof AuthenticatedAdminStudiosRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$studioSlug'
    | '/auth'
    | '/datenschutz'
    | '/home-office'
    | '/kontakt'
    | '/sitemap.xml'
    | '/admin'
    | '/$studioSlug/home-office'
    | '/$studioSlug/kontakt'
    | '/$studioSlug/'
    | '/admin/calendar'
    | '/admin/clients'
    | '/admin/einstellungen'
    | '/admin/marketing'
    | '/admin/studios'
    | '/api/public/ping'
    | '/api/public/whatsapp'
    | '/admin/'
    | '/admin/clients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/datenschutz'
    | '/home-office'
    | '/kontakt'
    | '/sitemap.xml'
    | '/$studioSlug/home-office'
    | '/$studioSlug/kontakt'
    | '/$studioSlug'
    | '/admin/calendar'
    | '/admin/clients'
    | '/admin/einstellungen'
    | '/admin/marketing'
    | '/admin/studios'
    | '/api/public/ping'
    | '/api/public/whatsapp'
    | '/admin'
    | '/admin/clients/$id'
  id:
    | '__root__'
    | '/'
    | '/$studioSlug'
    | '/_authenticated'
    | '/auth'
    | '/datenschutz'
    | '/home-office'
    | '/kontakt'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/$studioSlug/home-office'
    | '/$studioSlug/kontakt'
    | '/$studioSlug/'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/einstellungen'
    | '/_authenticated/admin/marketing'
    | '/_authenticated/admin/studios'
    | '/api/public/ping'
    | '/api/public/whatsapp'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/clients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioSlugRouteRoute: typeof StudioSlugRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  HomeOfficeRoute: typeof HomeOfficeRoute
  KontaktRoute: typeof KontaktRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicPingRoute: typeof ApiPublicPingRoute
  ApiPublicWhatsappRoute: typeof ApiPublicWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-office': {
      id: '/home-office'
      path: '/home-office'
      fullPath: '/home-office'
      preLoaderRoute: typeof HomeOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$studioSlug': {
      id: '/$studioSlug'
      path: '/$studioSlug'
      fullPath: '/$studioSlug'
      preLoaderRoute: typeof StudioSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$studioSlug/': {
      id: '/$studioSlug/'
      path: '/'
      fullPath: '/$studioSlug/'
      preLoaderRoute: typeof StudioSlugIndexRouteImport
      parentRoute: typeof StudioSlugRouteRoute
    }
    '/$studioSlug/kontakt': {
      id: '/$studioSlug/kontakt'
      path: '/kontakt'
      fullPath: '/$studioSlug/kontakt'
      preLoaderRoute: typeof StudioSlugKontaktRouteImport
      parentRoute: typeof StudioSlugRouteRoute
    }
    '/$studioSlug/home-office': {
      id: '/$studioSlug/home-office'
      path: '/home-office'
      fullPath: '/$studioSlug/home-office'
      preLoaderRoute: typeof StudioSlugHomeOfficeRouteImport
      parentRoute: typeof StudioSlugRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/whatsapp': {
      id: '/api/public/whatsapp'
      path: '/api/public/whatsapp'
      fullPath: '/api/public/whatsapp'
      preLoaderRoute: typeof ApiPublicWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ping': {
      id: '/api/public/ping'
      path: '/api/public/ping'
      fullPath: '/api/public/ping'
      preLoaderRoute: typeof ApiPublicPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/studios': {
      id: '/_authenticated/admin/studios'
      path: '/studios'
      fullPath: '/admin/studios'
      preLoaderRoute: typeof AuthenticatedAdminStudiosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/marketing': {
      id: '/_authenticated/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AuthenticatedAdminMarketingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/einstellungen': {
      id: '/_authenticated/admin/einstellungen'
      path: '/einstellungen'
      fullPath: '/admin/einstellungen'
      preLoaderRoute: typeof AuthenticatedAdminEinstellungenRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
  }
}

interface StudioSlugRouteRouteChildren {
  StudioSlugHomeOfficeRoute: typeof StudioSlugHomeOfficeRoute
  StudioSlugKontaktRoute: typeof StudioSlugKontaktRoute
  StudioSlugIndexRoute: typeof StudioSlugIndexRoute
}

const StudioSlugRouteRouteChildren: StudioSlugRouteRouteChildren = {
  StudioSlugHomeOfficeRoute: StudioSlugHomeOfficeRoute,
  StudioSlugKontaktRoute: StudioSlugKontaktRoute,
  StudioSlugIndexRoute: StudioSlugIndexRoute,
}

const StudioSlugRouteRouteWithChildren = StudioSlugRouteRoute._addFileChildren(
  StudioSlugRouteRouteChildren,
)

interface AuthenticatedAdminClientsRouteChildren {
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRoute
}

const AuthenticatedAdminClientsRouteChildren: AuthenticatedAdminClientsRouteChildren =
  {
    AuthenticatedAdminClientsIdRoute: AuthenticatedAdminClientsIdRoute,
  }

const AuthenticatedAdminClientsRouteWithChildren =
  AuthenticatedAdminClientsRoute._addFileChildren(
    AuthenticatedAdminClientsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRouteWithChildren
  AuthenticatedAdminEinstellungenRoute: typeof AuthenticatedAdminEinstellungenRoute
  AuthenticatedAdminMarketingRoute: typeof AuthenticatedAdminMarketingRoute
  AuthenticatedAdminStudiosRoute: typeof AuthenticatedAdminStudiosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
    AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRouteWithChildren,
    AuthenticatedAdminEinstellungenRoute: AuthenticatedAdminEinstellungenRoute,
    AuthenticatedAdminMarketingRoute: AuthenticatedAdminMarketingRoute,
    AuthenticatedAdminStudiosRoute: AuthenticatedAdminStudiosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioSlugRouteRoute: StudioSlugRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  HomeOfficeRoute: HomeOfficeRoute,
  KontaktRoute: KontaktRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicPingRoute: ApiPublicPingRoute,
  ApiPublicWhatsappRoute: ApiPublicWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
